def var = ""
pipeline{
	agent none
	options {
		gitLabConnection('gitlab.com')
		gitlabBuilds(builds: ['Build'])
	}
	triggers {
		gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All')
	}
	stages{
		stage("Prepare") {
		   agent { label 'hcink_vps' }
		   steps {
				 script {
					var = Eval.me( 'new Date()' )
				 }
		   }
		}
		stage("Build"){
			agent {
				dockerfile {
					label 'hcink_vps'
					filename '.ci/Dockerfiles/Build'
					additionalBuildArgs "--build-arg build_hash=\"${var}\""
				}
			}
			steps{
				sh "./build.sh"
				sh "./tests.sh"
			}
			post{
				success{
					junit testResults: 'test-run/results/*'
					archiveArtifacts artifacts: 'build/libimgc.so', fingerprint: true
					archiveArtifacts artifacts: 'build/imgc-tests', fingerprint: true
					archiveArtifacts artifacts: 'build/imgc-example', fingerprint: true
					updateGitlabCommitStatus name: 'Build', state: 'success'
				}
				failure{
					updateGitlabCommitStatus name: 'Build', state: 'failed'
				}
			}
		}
	}
}
