#ifndef INCLUDE_TORASU_MOD_IMGC_PIPELINE_NAMES_HPP_
#define INCLUDE_TORASU_MOD_IMGC_PIPELINE_NAMES_HPP_

// Alignment-pipeline
#define IMGC_PL_ALIGN "IMGC::PALIGN"

#endif // INCLUDE_TORASU_MOD_IMGC_PIPELINE_NAMES_HPP_
